# Generated by Django 5.0.14 on 2025-12-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0003_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liqpay_order_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('init', 'Init'), ('success', 'Success'), ('failed', 'Failed'), ('sandbox', 'Sandbox'), ('reversed', 'Reversed'), ('expired', 'Expired'), ('error', 'Error')], default='init', max_length=20)),
                ('liqpay_data', models.TextField()),
                ('liqpay_signature', models.TextField()),
                ('liqpay_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='card.order')),
            ],
        ),
    ]
